services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    restart: always
    ports: 
        - "80:80"
        - "443:443"
    volumes: 
        - ./nginx/conf.d:/etc/nginx/conf.d
  
  portfolio:
    image: bp91/vue-portfolio:latest
    container_name: portfolio
    expose: 
        - "8081"
    depends_on:
        - nginx
version: '2'
