services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    restart: always
    ports: 
        - "80:80"
        - "443:443"
    volumes: 
        - ./nginx/conf.d:/etc/nginx/conf.d
  
  frontend:
    build: frontend
    container_name: frontend
    expose: 
        - "8081"
    depends_on:
        - nginx
version: '2'